services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    ports:
      - 443:8443
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Password123@keycloak
      JDBC_PARAMS: "useSSL=false"
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - keycloak-network
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks:
      - keycloak-network
networks:
  keycloak-network: